### ISSUE TITLE
README.md 수정하기

### ISSUE THREAD

**Issue by soondl** [soondl/Project2#7]
github repository front page에 출력될 README.md파일 수정하기

**Comment by cocoapi** [comment]
추가 수정사항이 필요한 경우 코멘트 해주시기 바랍니다.

**Comment by soondl** [comment]
과제 요구사항중에

![wdwdwdwdwdwd](https://user-images.githubusercontent.com/36469244/39969692-cff5a2c8-571a-11e8-8873-3ce4a0751453.jpg)

README 에 위와 같은 내용을 추가하라는 요구사항이 있어서 해당 부분 추가하겠습니다.
